import { useEffect, useRef, useState, type FormEvent } from "react";
import { useSearchParams, Link } from "react-router-dom";
import { Cpu, Download, RefreshCw, ShieldCheck } from "lucide-react";
import { useProduct } from "../ProductContext";
import { listAgentTasks, OperatorApiError } from "../data/api";
import { getComputePreflight, getComputeHandoffs, prepareCompute, exportCompute, type ComputePreflight, type ComputeList } from "../data/computeApi";
import type { AgentTask } from "../agentDomain";
import "../styles/acceptance-compute.css";

const reasons:Record<string,string>={TASK_NOT_COMPLETED:'任务尚未完成',REVIEWED_OPERATOR_SNAPSHOT_REQUIRED:'需要真实上传项目的复核快照',EXPLICIT_ANNOTATION_REVIEW_REQUIRED:'需要新版逐样本验收及具名标注复核',GATE_NOT_PASS:'数据检查尚未通过，请先处理问题并复验',INCOMPLETE_DETERMINISTIC_CHECKS:'五类确定性检查尚未齐全',FROZEN_EVIDENCE_UNAVAILABLE:'冻结证据不可核验，请检查来源授权与文件',ACCEPTANCE_BINDING_MISMATCH:'复核要求摘要不匹配',CONTRACT_ACCEPTANCE_MISMATCH:'实际检查合同与复核要求不匹配',GATE_INPUT_MISMATCH:'检查结果不属于该冻结输入',SOURCE_AUTHORIZATION_INACTIVE:'数据来源授权已失效'};
export function ComputeHandoffPage(){
  const {activeWorkspace,activeProject}=useProduct();const [params,setParams]=useSearchParams();const taskId=params.get('task')??'';
  const workspaceId=activeWorkspace?.workspace_id??'',projectId=activeProject?.project_id??'';
  const scope={taskId,workspaceId,projectId};const generation=useRef(0);
  const [tasks,setTasks]=useState<AgentTask[]>([]),[preflight,setPreflight]=useState<ComputePreflight|null>(null),[items,setItems]=useState<ComputeList['items']>([]);
  const [busy,setBusy]=useState(false),[fresh,setFresh]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[unknownKey,setUnknownKey]=useState('');
  const [runtimeImage,setRuntimeImage]=useState(''),[version,setVersion]=useState(''),[workload,setWorkload]=useState<'TRAINING'|'EVALUATION'>('TRAINING');
  const [npu,setNpu]=useState(1),[cpu,setCpu]=useState(4),[memory,setMemory]=useState(16),[seconds,setSeconds]=useState(3600),[note,setNote]=useState(''),[attested,setAttested]=useState(false);
  useEffect(()=>{let active=true;setTasks([]);if(workspaceId&&projectId)void listAgentTasks(workspaceId,projectId).then(value=>{if(active)setTasks(value);}).catch(()=>{if(active)setError('任务列表读取失败，请恢复连接后重新选择项目。');});return()=>{active=false;};},[workspaceId,projectId]);
  useEffect(()=>{generation.current++;setPreflight(null);setItems([]);setFresh(false);setBusy(false);setUnknownKey('');setNotice('');setError('');setAttested(false);},[taskId,workspaceId,projectId]);
  async function refresh(){const token=generation.current;if(!taskId)return;setBusy(true);setFresh(false);setError('');try{
    const [next,list]=await Promise.all([getComputePreflight(scope),getComputeHandoffs(scope)]);if(token!==generation.current)return;
    setPreflight(next);setItems(list.items);setFresh(true);
    if(unknownKey){const existing=list.items.find(item=>item.record.request.request_key===unknownKey);setNotice(existing?'已通过 GET 找到该准备记录；未提交外部作业。':'暂未找到匹配记录，结果仍待对账。不会自动重放请求。');if(existing)setUnknownKey('');}
  }catch(reason){if(token===generation.current)setError(reason instanceof Error?reason.message:'读取失败；旧值已标为过期，不可用于交接。');}finally{if(token===generation.current)setBusy(false);}}
  async function prepare(event:FormEvent){event.preventDefault();if(!preflight||!fresh||busy||unknownKey||!attested)return;const token=generation.current;const key=crypto.randomUUID();setBusy(true);setError('');setNotice('');
    try{const record=await prepareCompute(scope,{request_key:key,expected_preflight_sha256:preflight.receipt_sha256,review_note:note,operator_attests_reviewed:true,workload,resources:{runtime_image:runtimeImage,cann_version:version,npu_count:npu,cpu_cores:cpu,memory_gib:memory,max_wall_seconds:seconds}});if(token!==generation.current)return;setItems(current=>[{read_status:'VERIFIED',record},...current.filter(item=>item.record.handoff_id!==record.handoff_id)]);setNotice('已保存离线算力交接申请；未分配 NPU、未运行训练、未上传图像。');setAttested(false);
    }catch(reason){if(token!==generation.current)return;setFresh(false);if(!(reason instanceof OperatorApiError&&[400,409,422].includes(reason.status)&&reason.code!=='COMPUTE_CONTRACT_HOLD'))setUnknownKey(key);setError(reason instanceof Error?reason.message:'准备结果未知，请仅通过 GET 查询记录。');}finally{if(token===generation.current)setBusy(false);}}
  async function download(id:string){const token=generation.current;setBusy(true);setError('');try{const record=await exportCompute(scope,id);if(token!==generation.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`${record.handoff_id}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(reason){if(token===generation.current){setFresh(false);setError(reason instanceof Error?reason.message:'无法核验导出；旧记录已暂停使用。');}}finally{if(token===generation.current)setBusy(false);}}
  return <div className="compute-page"><header><span><Cpu size={17}/> 标注复核之后 · 算力交接</span><h1>将这一版数据交给计算环境</h1><p>绑定已检查的冻结版本，准备昇腾 / CANN 环境所需的作业元数据。当前仅实现本地准备与导出，实际调度、数据挂载和运行由后续受控适配器接管。</p></header>
    <section className="compute-scope"><label>当前项目的任务<select value={taskId} onChange={e=>setParams({task:e.target.value})}><option value="">请选择任务</option>{taskId&&!tasks.some(task=>task.task_id===taskId)?<option value={taskId}>{taskId} · 待核验作用域</option>:null}{tasks.map(task=><option key={task.task_id} value={task.task_id}>{task.goal} · {task.execution_status}</option>)}</select></label><button disabled={!taskId||!workspaceId||!projectId||busy} onClick={()=>void refresh()}><RefreshCw size={15}/>{unknownKey?'仅查询准备结果':'核验输入与已有申请'}</button></section>
    {error?<p role="alert" className="acceptance-error">{error}{!fresh?' · STALE_HOLD / 尚不可交接':''}</p>:null}{notice?<p role="status">{notice}</p>:null}
    {preflight?<section className="compute-preflight"><h2>{fresh?(preflight.eligibility==='HOLD'?'暂不能交接':'可准备离线交接'):'上次读取已过期 · 不可使用'}</h2>{!fresh?<p>旧结果仅保留用于对账，不构成当前准入；请重新核验后继续。</p>:preflight.blockers.length?<ul>{preflight.blockers.map(reason=><li key={reason}>{reasons[reason]??reason}</li>)}</ul>:<p>冻结输入、逐样本复核、五类工具和 PASS 已核验。此状态不代表模型有效性、客户接受或 NPU 已就绪。</p>}<Link to="/workspace">返回工作簿整改与重新冻结</Link><details><summary>查看本次输入绑定</summary><pre>{JSON.stringify(preflight.binding,null,2)}</pre></details></section>:<p>先选择任务并核验。没有运行记录时，不会生成预设 PASS。</p>}
    <form onSubmit={e=>void prepare(e)}><fieldset disabled={busy||!fresh||preflight?.eligibility!=='READY_FOR_OFFLINE_HANDOFF'||Boolean(unknownKey)}><legend>离线作业申请</legend><div className="acceptance-fields">
      <label>用途<select value={workload} onChange={e=>setWorkload(e.target.value as typeof workload)}><option value="TRAINING">沙箱训练</option><option value="EVALUATION">沙箱评测</option></select></label><label>CANN 版本要求<input required value={version} onChange={e=>setVersion(e.target.value)} maxLength={40} placeholder="由集群管理员确认，不代表本机已安装"/></label>
      <label>固定镜像引用（必须含 @sha256）<input required value={runtimeImage} onChange={e=>setRuntimeImage(e.target.value)} placeholder="registry/runtime@sha256:…"/></label><label>NPU 数量<input type="number" required min={1} max={64} value={npu} onChange={e=>setNpu(Number(e.target.value))}/></label>
      <label>CPU 核数<input type="number" required min={1} max={256} value={cpu} onChange={e=>setCpu(Number(e.target.value))}/></label><label>内存 GiB<input type="number" required min={1} max={4096} value={memory} onChange={e=>setMemory(Number(e.target.value))}/></label><label>最长运行秒数<input type="number" required min={60} max={86400} value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label><label>人工复核与交接说明<textarea required minLength={8} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>
    </div><label className="acceptance-attestation"><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>我确认使用当前冻结版本准备沙箱算力申请；这里只登记和导出，不授权实际调度、费用或数据外发。</label><button type="submit" disabled={!attested}><ShieldCheck size={15}/>保存离线交接申请</button></fieldset></form>
    <section className="compute-records"><h2>已保存的交接申请</h2>{fresh&&!items.length?<p>本任务尚未创建申请。</p>:null}{items.map(item=><article key={item.record.handoff_id}><div><strong>{item.record.handoff_id}</strong><small>{fresh?item.read_status:'STALE_HOLD'} · PREPARED_NOT_SUBMITTED · NPU NOT_TESTED</small></div><button disabled={busy||!fresh||item.read_status!=='VERIFIED'} onClick={()=>void download(item.record.handoff_id)}><Download size={15}/>导出元数据合同</button></article>)}</section>
  </div>;
}
